[package]
name = "rtop"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29.11"
termion = "2.0.3"
chrono = "0.4"
crossterm = "0.27.0"
tui = "0.19.0"
thiserror = "1.0.57"
clap = { version = "4.5.1", features = ["derive"] }
