[package]
name = "rtop"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29"
termion = "1.5"
chrono = "0.4"
crossterm = "0.27"
tui = { version = "0.19", default-features = false, features = ["crossterm"] }