# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: rust-lang/rustup-action@v2
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test

  deploy:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: rust-lang/rustup-action@v2
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: rtop-${{ matrix.os }}
          path: target/release/rtop.exe
        if: matrix.os == 'windows-latest'
        
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: rtop-${{ matrix.os }}
          path: target/release/rtop
        if: matrix.os == 'macos-latest'